//
// Created by Andres on 11/20/2019.
//

#ifndef PROYECTOINDIVIDUAL_DIRECTORCONSTRUCCION_H
#define PROYECTOINDIVIDUAL_DIRECTORCONSTRUCCION_H


class DirectorConstruccion {

};


#endif //PROYECTOINDIVIDUAL_DIRECTORCONSTRUCCION_H
