//
// Created by Andres on 11/20/2019.
//

#ifndef PROYECTOINDIVIDUAL_CONSGRADERIALPREFERENCIAL_H
#define PROYECTOINDIVIDUAL_CONSGRADERIALPREFERENCIAL_H


class ConsGraderialPreferencial {

};


#endif //PROYECTOINDIVIDUAL_CONSGRADERIALPREFERENCIAL_H
