//
// Created by Andres on 11/20/2019.
//

#ifndef PROYECTOINDIVIDUAL_CONSGRADERIAGENERAL_H
#define PROYECTOINDIVIDUAL_CONSGRADERIAGENERAL_H


class ConsGraderiaGeneral {

};


#endif //PROYECTOINDIVIDUAL_CONSGRADERIAGENERAL_H
