//
// Created by Andres on 11/20/2019.
//

#ifndef PROYECTOINDIVIDUAL_CONSZONAPREFERENCIAL_H
#define PROYECTOINDIVIDUAL_CONSZONAPREFERENCIAL_H


class ConsZonaPreferencial {

};


#endif //PROYECTOINDIVIDUAL_CONSZONAPREFERENCIAL_H
